### ISSUE TITLE
RNBHouseParty Official AfroTech Platinum Party (ft. Bryan-Michael Cox)

### ISSUE THREAD

**Issue by sefanit** [helloayo/AfroTech-Events#12]
https://www.eventbrite.com/e/rnbhouseparty-official-afrotech-platinum-party-featuring-bryan-michael-cox-tickets-73450072143?ref=eios

**Comment by helloayo** [comment]
Hey I am only posting free events this year unless you want to work something out (free tickets, affiliate rev share etc.)
