### ISSUE TITLE
Request to advertise IDEO & IDEO.org networking event on Github

### ISSUE THREAD

**Issue by alainecisneros** [helloayo/AfroTech-Events#14]
Hey AfroTech!

IDEO and IDEO.org are hosting a networking event on Friday, Nov 8. We'd love to advertise the event on your GitHub page helloayo. We're excited to share our work with Black professionals in the area. 
https://www.eventbrite.com/e/innovation-design-a-conversation-with-ideo-ideoorg-designers-of-color-tickets-77411900077

Thanks for your time and let me know if you have any questions.

Best,
Jordan

**Comment by helloayo** [comment]
Added
