### ISSUE TITLE
Microsoft Networking Event @ AfroTech

### ISSUE THREAD

**Issue by MadeByUche** [helloayo/AfroTech-Events#15]
Microsoft will be hosting an invite-only Boat Cruise/Networking Event at AfroTech for technical talent (Software Engineers, Hardware Engineers, Security Engineers, Technical Program Managers, UX/UI Designers, etc.) who have 1+ years of industry (work) experience. 

Interested in attending? Let us know by completing the below Form.

*Note: this is not a registration page and completing the form does not guarantee admission to the event. Space is limited and those invited to attend will be notified directly.*

[Fill out this form](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR1SWy5cg3qVGgesG3cGzEOdUM05HSVY2TDJTQlBFN0RBNklKTDJJWFlDUS4u)

**Comment by helloayo** [comment]
@UcheAndrew can you give me info about the time and date of this event?

**Comment by helloayo** [comment]
I found the info. Posted Thanks!
