### ISSUE TITLE
the re·mix by Facebook x NextPlay Events

### ISSUE THREAD

**Issue by Jikpapa** [helloayo/AfroTech-Events#16]
On November 7th, Facebook and NextPlay will be hosting a 90s themed networking event. They will have senior tech leaders and recruiters from Black@ Facebook onsite, and special performances from Beychella choreographers. 

Interested in attending? 
Request an invite: facebookxnextplayeventsremix.splashthat.com/helloayo

**Comment by DKA007** [comment]
A LinkedN code is required. 

DKA

**Comment by Jikpapa** [comment]
Is that not allowed? @DKA007

**Comment by MoxieHampton** [comment]
You have to be invited to RSVP with the url provided.

**Comment by helloayo** [comment]
Added thanks!
