### ISSUE TITLE
Facebook Recruiter and Sourcer Mixer

### ISSUE THREAD

**Issue by Jikpapa** [helloayo/AfroTech-Events#17]
On November 8th, **Liz Wamai**, Head of Global Corporate Recruiting at Facebook, is hosting an event for recruiters  and sourcers during AfroTech. Come learn more about what we do and connect with our Black@ Facebook community. If you're interested, please request an invite. Space is limited. 

https://afrotechbuildcomminvite.splashthat.com

**Comment by helloayo** [comment]
Added thanks!!
