### ISSUE TITLE
Fivetran & dev/color Happy Hour After party

### ISSUE THREAD

**Issue by AmandaFivetran** [helloayo/AfroTech-Events#19]
Hello!

Please put our event on your list for November 8th? Thanks!!

Fivetran is hosting an AfroTech happy hour event in partnership with dev/color, a non-profit organization that aims to advance the careers of Black software engineers. The event is on Friday, November 8th, and is for AfroTech attendees and the Bay Area tech community. We'll have complimentary beverages, afrobeats from local DJ NOVA, swag and raffle prizes! RSVP online, space is limited! We look forward to connecting with you.

RSVP link: https://www.eventbrite.com/e/fivetran-x-devcolor-x-afrotech-happy-hour-after-party-tickets-78303380519

**Comment by byAaronC** [comment]
@helloayo I already submitted a pr for this event (and another one) ready for merge

https://github.com/helloayo/AfroTech-Events/pull/18#issue-332933780

**Comment by helloayo** [comment]
It's merged!
