### ISSUE TITLE
Impossible Foods Networking Event-

### ISSUE THREAD

**Issue by SiSiHenry** [helloayo/AfroTech-Events#20]
Description
MADE IN THE TOWN: Come network with the Impossible™ Black Employee Resource Group at Alamar  Kitchen and Bar on Thursday, November 7.

Cost: Free 
Eventbrite link:
https://www.eventbrite.com/e/impossibletm-black-employee-networking-event-tickets-78496528229 

Meet the team at Impossible™ and check out our current openings: impossiblefoods.com/careers
Currently we have over 110 positions open in sales, marketing, and strategic business roles, we are actively looking for candidates!   

ABOUT IMPOSSIBLE™
At Impossible Foods, we make meat, dairy and fish directly from plants. Our mission is to make the global food system truly sustainable by eliminating the need to make food from animals. Why? Animal agriculture uses a tremendous amount of the world's natural resources. In 2016, we launched our first product, the Impossible Burger. It's delicious, nutritious, and made using but a small fraction of the land, water and energy required to make meat from a cow.

Learn more: impossiblefoods.com

**Comment by helloayo** [comment]
Added Thanks!
