### ISSUE TITLE
Add American Express Event 

### ISSUE THREAD

**Issue by rosaswaby96** [helloayo/AfroTech-Events#21]
Hi! I would like to add the American Express event that will be taking place November 7th -- below are the details 

Event: A Night Out with American Express
Host: American Express
Location: Parliament (811 Washington St, Oakland, CA 94607) 
Time: 6PM - 9PM
Sign up Link: https://anightoutwithamericanexpress.splashthat.com/

**Comment by helloayo** [comment]
Added! Thanks!
