### ISSUE TITLE
AfroTech: Breakfast w. Goldman Sachs Engineering 

### ISSUE THREAD

**Issue by arianadavis** [helloayo/AfroTech-Events#23]
Event URL: https://recruiting360.avature.net/candidates/Register?projectId=12796&trk=public-post_share-update_update-text

More Info:[afrotech-2019.pdf](https://github.com/helloayo/AfroTech-Events/files/3795234/afrotech-2019.pdf)

**Comment by helloayo** [comment]
@YourMobileGeek Thanks!

**Comment by helloayo** [comment]
Added
